"""
Exporta todas as configurações do projeto.
"""

from src.common.config.settings import (  # noqa: F401
    # UART
    UART_PORT, UART_BAUDRATE, UART_TIMEOUT,
    UART_PARITY, UART_STOPBITS, UART_BYTESIZE,
    # Matrícula
    MATRICULA, MATRICULA_STR,
    # Comandos simplificados
    CMD_REQUEST_INT, CMD_REQUEST_FLOAT, CMD_REQUEST_STRING,
    CMD_SEND_INT, CMD_SEND_FLOAT, CMD_SEND_STRING,
    # MODBUS
    MODBUS_DEFAULT_SLAVE_ADDR, MODBUS_FUNC_READ, MODBUS_FUNC_WRITE,
    MODBUS_SUB_REQUEST_INT, MODBUS_SUB_REQUEST_FLOAT, MODBUS_SUB_REQUEST_STRING,
    MODBUS_SUB_SEND_INT, MODBUS_SUB_SEND_FLOAT, MODBUS_SUB_SEND_STRING,
    # Limites e retry
    MAX_STRING_LENGTH, RETRY_COUNT, RETRY_DELAY,
    MODBUS_RETRY_COUNT, MODBUS_RETRY_DELAY,
    # Semáforos Modelo 1
    M1_GPIO_GREEN, M1_GPIO_YELLOW, M1_GPIO_RED,
    M1_GPIO_BTN_PRINCIPAL, M1_GPIO_BTN_CRUZAMENTO,
    M1_GREEN_TIME, M1_YELLOW_TIME, M1_RED_TIME, M1_GREEN_MIN_TIME,
    # Semáforos Modelo 2
    M2_GPIO_BIT0, M2_GPIO_BIT1, M2_GPIO_BIT2,
    M2_GPIO_BTN_PRINCIPAL, M2_GPIO_BTN_CRUZAMENTO,
    M2_MAIN_GREEN_MIN, M2_MAIN_GREEN_MAX,
    M2_CROSS_GREEN_MIN, M2_CROSS_GREEN_MAX,
    M2_YELLOW_TIME, M2_ALL_RED_TIME,
    # Geral
    DEBOUNCE_MS, LOOP_INTERVAL,
)
